apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default

images:
- name: docker.m.daocloud.io/kubeflownotebookswg/pvcviewer-controller
  newName: docker.m.daocloud.io/kubeflownotebookswg/pvcviewer-controller
  newTag: v1.8.0
